FROM docker.io/bitnami/moodle:5.0

# Configura las variables que Bitnami espera usando las de Render
ENV MOODLE_DATABASE_HOST=${DATABASE_HOST} \
    MOODLE_DATABASE_PORT_NUMBER=${DATABASE_PORT} \
    MOODLE_DATABASE_USER=${DATABASE_USER} \
    MOODLE_DATABASE_NAME=${DATABASE_NAME} \
    MOODLE_DATABASE_PASSWORD=${DATABASE_PASSWORD} \
    MOODLE_DATABASE_TYPE=pgsql \
    MOODLE_DATABASE_SSL_MODE=require \
    ALLOW_EMPTY_PASSWORD=no \
    MOODLE_SKIP_BOOTSTRAP=no

EXPOSE 8080
VOLUME /bitnami/moodle

